### ISSUE TITLE
Toast: CCloseButton will overlap a long title

### ISSUE THREAD

**Issue by gbruins-notours** [chakra-ui/chakra-ui-vue#345]
**Describe the bug**
The CCloseButton ("X" icon) in the toast will overlap the toast title if the title is long enough.   There doesn't appear to be an elegant way for the client to fix this aside from writing some awkward CSS using multiple attribute selectors.  Something like this to add more right-side padding to the box that contains the title/description:

```css
[data-chakra-component="CToast"] [data-chakra-component="CAlertDescription"] {
  padding-right: 20px;
}
```

**To Reproduce**
1. Go to the [Toast demo page](https://vue.chakra-ui.com/toast)
2. In one of the "Editable Example" sections, change the 'title' to a long string of characters
3. Click the respective "Show Toast" button
4. See the "X" icon overlap the title
